name: Release to Stable
on:
  push:
    branches:
    - main
jobs:
  release:
    name: Push to main
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: npm install and build
      run: |
        npm install
        npm run build

    - name: Release to Stable
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: stable
        FOLDER: release
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: 'Release: ({sha}) {msg}'
